[export]
command:/usr/local/opnsense/scripts/cert-to-p12/cert-to-p12.sh --cert %s --outdir /root/cert-export --force
parameters:%s
type:script_output
message:Exporting certificate to PKCS#12 (.p12) format
description:Export certificate as PKCS#12 (.p12)

[export-legacy]
command:/usr/local/opnsense/scripts/cert-to-p12/cert-to-p12.sh --cert %s --outdir /root/cert-export --legacy --force
parameters:%s
type:script_output
message:Exporting certificate to PKCS#12 (.p12) with legacy mode
description:Export certificate as PKCS#12 (.p12) legacy
