<?php
/**
 * cert-export.php — OPNsense certificate .p12 download via HTTP API
 *
 * Serves exported .p12 files generated by cert-to-p12.sh through an
 * authenticated HTTP endpoint. Authentication uses the same API key/secret
 * mechanism as the OPNsense REST API (System -> Access -> Users -> API key).
 *
 * INSTALL:
 *   mkdir -p /usr/local/www/cert-export
 *   cp cert-export.php /usr/local/www/cert-export/index.php
 *
 * USAGE:
 *   curl -u "<api_key>:<api_secret>" \
 *     "https://opnsense/cert-export/?cert=<name>"
 *
 *   Or with query-string params (less secure, HTTPS only):
 *   curl "https://opnsense/cert-export/?cert=<name>&apikey=<key>&apisecret=<secret>"
 *
 * RESPONSE:
 *   200 — .p12 file as application/x-pkcs12 binary
 *   4xx — JSON error
 */

$exportDir = '/root/cert-export';
$configXml = '/conf/config.xml';

function jsonError($msg, $code) {
    http_response_code($code);
    header('Content-Type: application/json');
    echo json_encode(['error' => $msg]) . "\n";
    exit;
}

function loadApiKeys($configXml) {
    $keys = [];
    if (!file_exists($configXml)) return $keys;
    $xml = simplexml_load_file($configXml);
    if (!$xml || !isset($xml->user)) return $keys;
    foreach ($xml->user as $user) {
        if (!isset($user->APIkey)) continue;
        foreach ($user->APIkey as $apiKey) {
            $k = (string)$apiKey->key;
            $s = (string)$apiKey->secret;
            if ($k && $s) $keys[$k] = $s;
        }
    }
    return $keys;
}

function authenticate($keys) {
    $apiKey = null;
    $apiSecret = null;

    $authHeader = $_SERVER['HTTP_AUTHORIZATION']
        ?? $_SERVER['REDIRECT_HTTP_AUTHORIZATION']
        ?? '';

    if (preg_match('/^Basic\s+(.+)$/i', $authHeader, $m)) {
        $decoded = base64_decode($m[1]);
        if ($decoded && strpos($decoded, ':') !== false) {
            list($apiKey, $apiSecret) = explode(':', $decoded, 2);
        }
    }

    if (!$apiKey || !$apiSecret) {
        $apiKey = $_GET['apikey'] ?? null;
        $apiSecret = $_GET['apisecret'] ?? null;
    }

    if (!$apiKey || !$apiSecret) {
        jsonError('Authentication required. Use Basic auth (API key:secret) or query params.', 401);
    }

    if (!isset($keys[$apiKey]) || !hash_equals($keys[$apiKey], $apiSecret)) {
        jsonError('Invalid API key or secret.', 403);
    }
}

header('X-Content-Type-Options: nosniff');
header('X-Frame-Options: DENY');

$apiKeys = loadApiKeys($configXml);
if (empty($apiKeys)) {
    jsonError('No API keys configured. Create one in System -> Access -> Users.', 500);
}

authenticate($apiKeys);

$certName = $_GET['cert'] ?? null;
if (!$certName) {
    jsonError('Missing "cert" parameter. Usage: ?cert=<name>', 400);
}

$sanitized = preg_replace('/[^a-zA-Z0-9._-]/', '_', $certName);
$sanitized = preg_replace('/__+/', '_', $sanitized);
$sanitized = trim($sanitized, '_');
if (empty($sanitized)) {
    jsonError('Invalid certificate name.', 400);
}

$p12File = $exportDir . '/' . $sanitized . '.p12';

if (!file_exists($p12File)) {
    jsonError("File not found: {$sanitized}.p12. Run cert-to-p12.sh first.", 404);
}

$fileSize = filesize($p12File);
if ($fileSize === false || $fileSize === 0) {
    jsonError('File is empty or unreadable.', 500);
}

header('Content-Type: application/x-pkcs12');
header('Content-Disposition: attachment; filename="' . $sanitized . '.p12"');
header('Content-Length: ' . $fileSize);
header('Cache-Control: no-cache, no-store, must-revalidate');
header('Pragma: no-cache');
header('Expires: 0');

readfile($p12File);
