<?php
/**
 * cert-export.php — OPNsense certificate .p12 download via HTTP API
 *
 * Serves exported .p12 files generated by cert-to-p12.sh through an
 * authenticated HTTP endpoint. Authentication uses the same API key/secret
 * mechanism as the OPNsense REST API (System -> Access -> Users -> API key).
 *
 * INSTALL:
 *   mkdir -p /usr/local/www/cert-export
 *   cp cert-export.php /usr/local/www/cert-export/index.php
 *
 * USAGE:
 *   curl -u "<api_key>:<api_secret>" \
 *     "https://opnsense/cert-export/?cert=<name>"
 *
 *   Or with query-string params (less secure, HTTPS only):
 *   curl "https://opnsense/cert-export/?cert=<name>&apikey=<key>&apisecret=<secret>"
 *
 *   To download the corresponding password file instead:
 *   curl -u "<api_key>:<api_secret>" \
 *     "https://opnsense/cert-export/?cert=<name>&password=1"
 *
 * RESPONSE:
 *   200 — .p12 file as application/x-pkcs12 binary (or text/plain for password)
 *   4xx — JSON error
 */

// Try www-accessible paths first, fall back to /root/ for backward compat
$exportDir = '/var/cert-export';
if (!is_dir($exportDir) && is_dir('/root/cert-export')) {
    $exportDir = '/root/cert-export';
}
$configXml = '/conf/config.xml';

function jsonError($msg, $code) {
    http_response_code($code);
    header('Content-Type: application/json');
    echo json_encode(['error' => $msg]) . "\n";
    exit;
}

function loadApiKeys($configXml) {
    $keys = [];
    if (!file_exists($configXml)) return $keys;
    $xml = simplexml_load_file($configXml);
    if (!$xml) return $keys;

    // Use xpath to find all <user> elements (handles namespaces correctly)
    // Note: <user> is at /opnsense/system/user, NOT at /opnsense/user
    $users = $xml->xpath('//user');
    if (!$users) return $keys;

    foreach ($users as $user) {
        // Format 1: <APIkey><key>...</key><secret>...</secret></APIkey>
        // Rare format, seen in some OPNsense versions
        $apikeyNodes = $user->xpath('APIkey');
        if ($apikeyNodes) {
            foreach ($apikeyNodes as $apiKey) {
                $k = (string)$apiKey->key;
                $s = (string)$apiKey->secret;
                if ($k && $s) $keys[$k] = $s;
            }
        }

        // Format 2 (OPNsense native — see ApiKeyField.php):
        //   <apikeys>key1|$6$hash1
        //   key2|$6$hash2</apikeys>
        // Pipe-delimited text, multiple keys separated by newlines.
        // Hash is crypt($raw_secret, '$6$') — SHA-512 with empty salt.
        $apikeysNodes = $user->xpath('apikeys');
        if ($apikeysNodes) {
            foreach ($apikeysNodes as $apikeys) {
                $text = (string)$apikeys;
                foreach (array_filter(explode("\n", $text)) as $line) {
                    $parts = explode('|', $line, 2);
                    if (count($parts) === 2 && $parts[0] && $parts[1]) {
                        $keys[$parts[0]] = $parts[1];
                    }
                }
            }
        }
    }
    return $keys;
}

function verifySecret($stored, $plaintext) {
    // If stored secret starts with '$' it's a SHA-512 crypt hash (e.g. $6$...)
    if (strpos($stored, '$') === 0) {
        return hash_equals($stored, crypt($plaintext, $stored));
    }
    // Plaintext comparison (legacy)
    return hash_equals($stored, $plaintext);
}

function authenticate($keys) {
    $apiKey = null;
    $apiSecret = null;

    $authHeader = $_SERVER['HTTP_AUTHORIZATION']
        ?? $_SERVER['REDIRECT_HTTP_AUTHORIZATION']
        ?? '';

    if (preg_match('/^Basic\s+(.+)$/i', $authHeader, $m)) {
        $decoded = base64_decode($m[1]);
        if ($decoded && strpos($decoded, ':') !== false) {
            list($apiKey, $apiSecret) = explode(':', $decoded, 2);
        }
    }

    if (!$apiKey || !$apiSecret) {
        $apiKey = $_GET['apikey'] ?? null;
        $apiSecret = $_GET['apisecret'] ?? null;
    }

    if (!$apiKey || !$apiSecret) {
        jsonError('Authentication required. Use Basic auth (API key:secret) or query params.', 401);
    }

    if (!isset($keys[$apiKey]) || !verifySecret($keys[$apiKey], $apiSecret)) {
        jsonError('Invalid API key or secret.', 403);
    }
}

header('X-Content-Type-Options: nosniff');
header('X-Frame-Options: DENY');

$apiKeys = loadApiKeys($configXml);
if (empty($apiKeys)) {
    jsonError('No API keys configured. Create one in System -> Access -> Users.', 500);
}

authenticate($apiKeys);

$certName = $_GET['cert'] ?? null;
if (!$certName) {
    jsonError('Missing "cert" parameter. Usage: ?cert=<name>', 400);
}

$sanitized = preg_replace('/[^a-zA-Z0-9._-]/', '_', $certName);
$sanitized = preg_replace('/__+/', '_', $sanitized);
$sanitized = trim($sanitized, '_');
if (empty($sanitized)) {
    jsonError('Invalid certificate name.', 400);
}

// Support serving the .password file alongside the .p12
$servePassword = ($_GET['password'] ?? '') === '1';

if ($servePassword) {
    $passwordFile = $exportDir . '/' . $sanitized . '.password';
    if (!file_exists($passwordFile)) {
        jsonError("Password file not found: {$sanitized}.password. Run cert-to-p12.sh first.", 404);
    }
    $fileSize = filesize($passwordFile);
    if ($fileSize === false || $fileSize === 0) {
        jsonError('Password file is empty or unreadable.', 500);
    }
    header('Content-Type: text/plain; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $sanitized . '.password"');
    header('Content-Length: ' . $fileSize);
    header('Cache-Control: no-cache, no-store, must-revalidate');
    header('Pragma: no-cache');
    header('Expires: 0');
    readfile($passwordFile);
    exit;
}

$p12File = $exportDir . '/' . $sanitized . '.p12';

if (!file_exists($p12File)) {
    jsonError("File not found: {$sanitized}.p12. Run cert-to-p12.sh first.", 404);
}

$fileSize = filesize($p12File);
if ($fileSize === false || $fileSize === 0) {
    jsonError('File is empty or unreadable.', 500);
}

header('Content-Type: application/x-pkcs12');
header('Content-Disposition: attachment; filename="' . $sanitized . '.p12"');
header('Content-Length: ' . $fileSize);
header('Cache-Control: no-cache, no-store, must-revalidate');
header('Pragma: no-cache');
header('Expires: 0');

readfile($p12File);
